title: Gabriel Bird
author: Gabriel Bird
email: gabriel.jackson.bird@gmail.com
description: > # this means to ignore newlines until "baseurl:"
    Tufts University, Class of 2019
	  \n
	  BS: Cognitive and Brain Sciences
	  \n

# social links
twitter_username: _______
github_username:  ______

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-minimal
